[platformio]
src_dir = src/firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Garante a exportação do banco de dados de compilação e caminhos de cabeçalho
build_flags = 
    -Isrc/firmware

; Bibliotecas necessárias para os sensores e periféricos do robô
lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit Unified Sensor @ ^1.1.14

; -------------------------------------------------------------------------
; UPLOAD VIA WI-FI (OTA):
; Descomente as duas linhas abaixo quando for gravar SEM O CABO USB:
upload_protocol = espota
upload_port = 192.168.4.1
; -------------------------------------------------------------------------